### ISSUE TITLE
Challenges with data connection

### ISSUE THREAD

**Issue by LizbethSage** [MaheshSQL/CognitiveServicesDemos#1]
Hi There, 

Thanks for this excellent demo- this is exactly the sort of thing I have been looking for.  Only problem is I haven't been able to get it to work fully.  Conscious I'm a relative newbie in this space so I fully expect I've done something wrong :).

Steps I've followed:
- I've created and provisioned a Cognitive Services resource
- I've downloaded the source data (hotels and cars)
- I've downloaded the PowerBI dashboard
- I've opened the dashboard, selected transform and entered the relative parameters (endpoint, local source file location, number of queries, API key). 

And this is where I hit an issue.

![image](https://user-images.githubusercontent.com/98723853/158726090-7c344bce-9066-416e-9e65-0d00e053bcb6.png)

Could you please let me know if this is something you think could be wrong on my end or if there might be an issue in the query order?  When I open the file, it already has a warning in place saying there are pending changes to the query so I was wondering if it might be something to do with that. 

Really appreciate your help.

Lizbeth

**Comment by MaheshSQL** [comment]
Hi, please change the below setting in Ppwer BI Desktop for the demo to run.

**Options --> CURRENT FILE --> Privacy then setting the Privacy Level to "ignore the privacy levels.."**

Thanks.
